src/Strand/strand/models/blood_pressure.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc

# Local application imports
from strand import db


class BloodPressure(db.Model):
    __tablename__ = 'BloodPressure'
    id = db.Column('id', db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True, default=datetime.utcnow)
    systolic = db.Column('Systolic', db.Integer, nullable=False)
    diastolic = db.Column('Diastolic', db.Integer, nullable=False)
    notes = db.Column('Notes', db.String(300))
    # foreign key name is table name.id
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

    @staticmethod
    def newest(num):
        return BloodPressure.query.order_by(desc(BloodPressure.date)).limit(num)

    @staticmethod
    def all():
        return BloodPressure.query.order_by(desc(BloodPressure.date))


# def __repr__(self):
#    return "<Bookmark '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'date': self.date,
            'systolic': self.systolic,
            'diastolic': self.diastolic,
            'notes': self.notes
         }

src/Strand/strand/models/blood_pressure_log.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc

# Local application imports
from strand import db


class BloodPressureLog(db.Model):
    __tablename__ = 'BloodPressureLog'
    id = db.Column('id', db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True, default=datetime.utcnow)
    systolic = db.Column('Systolic', db.Integer, nullable=False)
    diastolic = db.Column('Diastolic', db.Integer, nullable=False)
    heart_rate = db.Column('HeartRate', db.Integer, nullable=False)
    notes = db.Column('Notes', db.String(300))
    # foreign key name is table name.id
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

    @staticmethod
    def newest(num):
        return BloodPressureLog.query.order_by(desc(BloodPressureLog.date)).limit(num)

    @staticmethod
    def all():
        return BloodPressureLog.query.order_by(desc(BloodPressureLog.date))

    @staticmethod
    def get_by_date(date_string):
        return BloodPressureLog.query.filter(BloodPressureLog.date == date_string)


# def __repr__(self):
#    return "<Bookmark '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'date': self.date,
            'systolic': self.systolic,
            'diastolic': self.diastolic,
            'heart_rate': self.heart_rate,
            'notes': self.notes
         }

src/Strand/strand/models/body_part_metadata.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc
from sqlalchemy.orm import relationship

# Local application imports
from strand import db


class BodyPartMetadata(db.Model):
    __tablename__ = 'BodyPartMetadata'
    id = db.Column('id', db.Integer, primary_key=True)
    body_part_name = db.Column('BodyPartName', db.String(255), nullable=False)
    notes = db.Column('Notes', db.String(300))

    @staticmethod
    def newest(num):
        return BodyPartMetadata.query.order_by(desc(BodyPartMetadata.date)).limit(num)

    @staticmethod
    def all():
        return BodyPartMetadata.query.order_by(desc(BodyPartMetadata.date))

    # def __repr__(self):
    #    return "<Bookmark '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'body_part_name': self.body_part_name,
            'notes': self.notes
        }

src/Strand/strand/models/exercise_log.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc

# Local application imports
from strand import db


class ExerciseLog(db.Model):
    __tablename__ = 'ExerciseLog'
    id = db.Column('id', db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True, default=datetime.utcnow)
    completed_flag = db.Column('CompletedFlag', db.Boolean, nullable=False)
    time_seconds = db.Column('TimeSeconds', db.Integer, nullable=True)
    weight_kg = db.Column('WeightKG', db.Float, nullable=True)
    reps = db.Column('Reps', db.Integer, nullable=True)
    notes = db.Column('Notes', db.String(300))
    # foreign key name is table name.id
    exercise_id = db.Column(db.Integer, db.ForeignKey('ExerciseMetadata.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

    @staticmethod
    def newest(num):
        return ExerciseLog.query.order_by(desc(ExerciseLog.date)).limit(num)

    @staticmethod
    def all():
        return ExerciseLog.query.order_by(desc(ExerciseLog.date))

    # @staticmethod
    # def __repr__(self):
    #    return "<Weight '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'date': self.date,
            'completed_flag': self.completed_flag,
            'time_seconds': self.time_seconds,
            'weight_kg': self.weight_kg,
            'reps': self.reps,
            'notes': self.notes
         }

src/Strand/strand/models/exercise_metadata.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc
from sqlalchemy.orm import relationship

# Local application imports
from strand import db


class ExerciseMetadata(db.Model):
    __tablename__ = 'ExerciseMetadata'
    id = db.Column('id', db.Integer, primary_key=True)
    exercise_name = db.Column('ExerciseName', db.String(255), nullable=False)
    notes = db.Column('Notes', db.String(300))
    # foreign key name is table name.id
    body_part_worked_1 = db.Column(db.Integer, db.ForeignKey('BodyPartMetadata.id'), nullable=False)
    body_part_worked_2 = db.Column(db.Integer, db.ForeignKey('BodyPartMetadata.id'), nullable=True)
    body_part_worked_3 = db.Column(db.Integer, db.ForeignKey('BodyPartMetadata.id'), nullable=True)

    body_part_worked_1_rel = db.relationship('BodyPartMetadata'
                                             , backref='part1'
                                             , foreign_keys=[body_part_worked_1])
    body_part_worked_2_rel = db.relationship('BodyPartMetadata'
                                             , backref='part2'
                                             , foreign_keys=[body_part_worked_2])
    body_part_worked_3_rel = db.relationship('BodyPartMetadata'
                                             , backref='part3'
                                             , foreign_keys=[body_part_worked_3])

    # backref can be anything, either the class name or table name
    exercise_log_rel = db.relationship('ExerciseLog', backref='ExerciseMetadata', lazy='dynamic')

    @staticmethod
    def newest(num):
        return ExerciseMetadata.query.order_by(desc(ExerciseMetadata.date)).limit(num)

    @staticmethod
    def all():
        return ExerciseMetadata.query.order_by(desc(ExerciseMetadata.date))

    # @staticmethod
    # def __repr__(self):
    #    return "<Weight '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'date': self.exercise_name,
            'body_part_worked_1': self.body_part_worked_1,
            'body_part_worked_2': self.body_part_worked_2,
            'body_part_worked_3': self.body_part_worked_3,
            'notes': self.notes
        }

src/Strand/strand/models/metrics_log.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc

# Local application imports
from strand import db


class MetricsLog(db.Model):
    __tablename__ = 'MetricsLog'
    id = db.Column('id', db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True, default=datetime.utcnow)
    weight_kg = db.Column('WeightKG', db.Float, nullable=True)
    bmi = db.Column('BMI', db.Float, nullable=True)
    body_fat_percent = db.Column('BodyFatPercent', db.Float, nullable=True)
    notes = db.Column('Notes', db.String(300))
    # foreign key name is table name.id
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

    @staticmethod
    def newest(num):
        return MetricsLog.query.order_by(desc(MetricsLog.date)).limit(num)

    @staticmethod
    def all():
        return MetricsLog.query.order_by(desc(MetricsLog.date))

    # @staticmethod
    # def __repr__(self):
    #    return "<Weight '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'date': self.date,
            'weight_kg': self.weight_kg,
            'bmi': self.bmi,
            'body_fat_percent': self.body_fat_percent,
            'notes': self.notes
         }

src/Strand/strand/models/user.py
# Standard library imports

# Third party imports
from flask_login import UserMixin
from sqlalchemy import func
from passlib.hash import bcrypt
from werkzeug.security import check_password_hash, generate_password_hash

# Local application imports
from strand import db


# Flask login requires User class to implement a few methods.
# UserMixin provides default implementations
class User(db.Model, UserMixin):
    __tablename__ = 'User'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    password_hash = db.Column(db.String(255), nullable=False)

    # backref can be anything, either the class name or table name
    weight_rel = db.relationship('MetricsLog', backref='user', lazy='dynamic')
    blood_pressure_rel = db.relationship('BloodPressureLog', backref='user', lazy='dynamic')

    #def __repr__(self):
    #    return "<User %r>" % self.username

    @property
    def password(self):
        raise AttributeError('password: Write-only field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter(func.lower(User.username) == func.lower(username)).first()

    @property
    def serialize(self):
        return {
            'id': self.id,
            'username': self.username,
            'email': self.email
        }

    # Not used
    @staticmethod
    def hash_password(password):
        return bcrypt.using(rounds=13).hash(password)

    # Not used
    def verify_password(self, password):
        return bcrypt.verify(password, self.password_hash)

src/Strand/strand/models/weight.py
# Standard library imports
from datetime import datetime

# Third party imports
from sqlalchemy import desc

# Local application imports
from strand import db


class Weight(db.Model):
    __tablename__ = 'Weight'
    id = db.Column('id', db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True, default=datetime.utcnow)
    body_weight = db.Column('Weight', db.Float, nullable=True)
    bmi = db.Column('BMI', db.Float, nullable=True)
    body_fat_percent = db.Column('BodyFatPercent', db.Float, nullable=True)
    notes = db.Column('Notes', db.String(300))
    # foreign key name is table name.id
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

    @staticmethod
    def newest(num):
        return Weight.query.order_by(desc(Weight.date)).limit(num)

    @staticmethod
    def all():
        return Weight.query.order_by(desc(Weight.date))

    # @staticmethod
    # def __repr__(self):
    #    return "<Weight '{}: '{}'>".format(self.description, self.url)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'date': self.date,
            'body_weight': self.body_weight,
            'bmi': self.bmi,
            'body_fat_percent': self.body_fat_percent,
            'notes': self.notes
         }

src/Strand/strand/__init__.py
from flask import Flask
from .config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


# Global DB object
db = SQLAlchemy()
# Global login manager object
login_manager = LoginManager()
application = Config.APPLICATION


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)

    # Help prevent users’ sessions from being stolen
    login_manager.session_protection = "Strong"
    # Redirects any view decorated with login_required to this one, with the next variable set
    login_manager.login_view = "core.sign_in"
    # Associate the login object to current app, so we can use login_required and other features
    login_manager.init_app(app)

    return app

src/Strand/strand/views/core.py
from flask import render_template
from flask import Blueprint, flash, redirect, url_for, request
from flask_login import login_required, login_user, logout_user, current_user
from ..models.user import User
from ..models.blood_pressure_log import BloodPressureLog
from ..viewmodels.blood_pressure_log_form import BloodPressureLogForm
from ..viewmodels.login_form import LoginForm
from ..viewmodels.signup_form import SignupForm
from ..viewmodels.login_manager import load_user
from .. import db


# <name of blueprint to be registered> = Blueprint('<friendly name to be used in URLs>', __name__)
core_blueprint = Blueprint('core', __name__)


@core_blueprint.route('/')
@core_blueprint.route('/index')
def index():
    return render_template('index.html')


@core_blueprint.route('/bloodpressure', methods=['GET', 'POST'])
@login_required
def log_blood_pressure():
    local_form = BloodPressureLogForm()
    recent = BloodPressureLog.newest(5)
    if request.method == 'POST' and request.form.post['action'] == 'Download':
        if local_form.validate_on_submit():
            blood_pressure_entry = BloodPressureLog(
                systolic=int(local_form.systolic.data),
                diastolic=int(local_form.diastolic.data),
                heart_rate=int(local_form.heart_rate.data),
                date=local_form.date.data,
                user=current_user,
                notes=local_form.notes.data,
            )
        db.session.add(blood_pressure_entry)
        db.session.commit()
        flash("Blood pressure entry added!")
        return redirect(url_for('core.log_blood_pressure'))
    return render_template('blood_pressure_log.html'
                           , form=local_form
                           , title_bar='Add blood pressure details'
                           , recent=recent)


@core_blueprint.route('/login', methods=['GET', 'POST'])
def sign_in():
    local_form = LoginForm()
    # if request.method == 'POST':
    if local_form.validate_on_submit():
        username = local_form.username.data
        password = local_form.password.data
        cur_user = User.get_by_username(username)
        if cur_user is not None and cur_user.check_password(password):
            login_user(cur_user, local_form.remember_me.data)
            flash("User '{}' logged in successfully!".format(username))
            return redirect(request.args.get('next') or url_for('core.index'))
        else:
            flash("Incorrect username or password")
    return render_template('login.html', form=local_form, title_bar='User Login')


@core_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    local_form = SignupForm()
    # if request.method == 'POST':
    if local_form.validate_on_submit():
        user_entry = User(
            email=local_form.email.data,
            username = local_form.username.data,
            password = local_form.password.data,
        )
        db.session.add(user_entry)
        db.session.commit()
        flash("Welcome! '{}'! Please login.".format(local_form.username.data))
        return redirect(url_for('core.sign_in'))
    return render_template('signup.html', form=local_form, title_bar='User Signup')


@core_blueprint.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('core.index'))

src/Strand/strand/templates/base.html
<!doctype html>

<html class="no-js" lang="">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Strand</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/css/variables.css">
    <link rel="stylesheet" href="../static/css/normalize.min.css">
    <link rel="stylesheet" href="../static/css/main.css">
    <link rel="stylesheet" href="../static/css/custom.css">
    <link rel="stylesheet" href="../static/css/custom_index.css">

    <script src="../static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>

    <body>
        <div class="left-panel">
            <div class="logo">
                <h1>
                    <a href="{{ url_for('core.index') }}">Strand</a>
                </h1>
            </div>
            <div class="navbar">
            {% block side_block %}
                <a href="{{ url_for('core.log_blood_pressure') }}">Blood pressure</a>
            {% endblock %}
            </div>
        </div>
        <div class="main-container">
            <div class="menubar">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('core.logout') }}">Logout</a>
                    <a href="{{ url_for('core.index') }}">Welcome, {{ current_user.username }}!</a>
                {% else %}
                    <a href="{{ url_for('core.sign_in') }}">Sign in</a>
                {% endif %}
                <a href="{{ url_for('core.signup') }}">Sign up</a>
                <a href="{{ url_for('core.index') }}">Home</a>
            </div>
            <div class="main">
                {%block content %}
                {% endblock %}
            </div>
        </div>
        <div class="footer-panel">
            <p class="credit">Photo by Maria Shanina on Unsplash</p>
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="../static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="../static/js/main.js"></script>
    </body>
</html>

src/Strand/strand/templates/blood_pressure.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<header>
    <h1>Add blood pressure details</h1>
</header>
<form action="" method="post">
    {{form.hidden_tag()}}
    <table>
        {{ render_field(form.systolic, size=50) }}
        {{ render_field(form.diastolic, size=50) }}
        {{ render_field(form.date, size=50) }}
        {{ render_field(form.notes, size=50) }}
    </table>
    <button>Submit</button>
<h1>Recent entries</h1>
    <table>
        <tr>
            <th class="field-label">Date</th>
            <th class="field-label">Blood pressure (systolic)</th>
            <th class="field-label">Blood pressure (diastolic)</th>
        </tr>
        {% for entry in recent %}
        <tr>
            <td class="field-label">{{ entry.date.strftime('%Y-%m-%d') }}</td>
            <td class="field-label">{{ entry.systolic }} / {{ entry.diastolic }}</td>
        </tr>
        {% endfor %}
    </table>
</form>
{% endblock %}

src/Strand/strand/templates/blood_pressure_log.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<div class="main-container-log-block">
    <header>
        <h1 class="entry-header">Blood pressure</h1>
    </header>
    <form action="" method="post">
        {{form.hidden_tag()}}
        <table>
            {{ render_field(form.systolic, size=50) }}
            {{ render_field(form.diastolic, size=50) }}
            {{ render_field(form.heart_rate, size=50) }}
            {{ render_field(form.date, size=50) }}
            {{ render_field(form.notes, size=50) }}
        </table>
        <div class="panel-body">
          <input type ="submit" name="action" value="Submit">
      </div>
      <div class="panel-body">
          <input type ="submit" name="action" value="Histogram">
      </div>
      <div class="panel-body">
          <input type ="submit" name="action" value="Search">
      </div>
        <!--<button>Submit</button>-->
    <h1 class="entry-header">Recent entries</h1>
        <table>
            <tr>
                <th class="static-table-header">Date</th>
                <th class="static-table-header">Systolic/Diastolic/Heart rate</th>
            </tr>
            {% for entry in recent %}
            <tr>
                <td class="static-table-data">{{ entry.date.strftime('%d-%b-%Y') }}</td>
                <td class="static-table-data">{{ entry.systolic }} / {{ entry.diastolic }} / {{ entry.heart_rate }}</td>
            </tr>
            {% endfor %}
        </table>
    </form>
</div>
{% endblock %}

src/Strand/strand/templates/body_part_metadata.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<header>
    <h1>Add weight details</h1>
</header>
<form action="" method="post">
    {{form.hidden_tag()}}
    <table>
        {{ render_field(form.body_weight, size=50) }}
        {{ render_field(form.body_fat_percent, size=50) }}
        {{ render_field(form.date, size=50) }}
        {{ render_field(form.notes, size=50) }}
    </table>
    <button>Submit</button>
<h1>Recent entries</h1>
    <table>
        <tr>
            <th class="field-label">Date</th>
            <th class="field-label">Weight (KG)</th>
            <th class="field-label">Body Fat Percent</th>
        </tr>
        {% for entry in recent %}
        <tr>
            <td class="field-label">{{ entry.date.strftime('%Y-%m-%d') }}</td>
            <td class="field-label">{{ entry.body_weight }}</td>
            <td class="field-label">{{ entry.body_fat_percent }}</td>
        </tr>
        {% endfor %}
    </table>
</form>
{% endblock %}

src/Strand/strand/templates/exercise_log.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<header>
    <h1>Add blood pressure details</h1>
</header>
<form action="" method="post">
    {{form.hidden_tag()}}
    <table>
        {{ render_field(form.systolic, size=50) }}
        {{ render_field(form.diastolic, size=50) }}
        {{ render_field(form.date, size=50) }}
        {{ render_field(form.notes, size=50) }}
    </table>
    <button>Submit</button>
<h1>Recent entries</h1>
    <table>
        <tr>
            <th class="field-label">Date</th>
            <th class="field-label">Blood pressure (systolic)</th>
            <th class="field-label">Blood pressure (diastolic)</th>
        </tr>
        {% for entry in recent %}
        <tr>
            <td class="field-label">{{ entry.date.strftime('%Y-%m-%d') }}</td>
            <td class="field-label">{{ entry.systolic }} / {{ entry.diastolic }}</td>
        </tr>
        {% endfor %}
    </table>
</form>
{% endblock %}

src/Strand/strand/templates/exercise_metadata.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<header>
    <h1>Add weight details</h1>
</header>
<form action="" method="post">
    {{form.hidden_tag()}}
    <table>
        {{ render_field(form.body_weight, size=50) }}
        {{ render_field(form.body_fat_percent, size=50) }}
        {{ render_field(form.date, size=50) }}
        {{ render_field(form.notes, size=50) }}
    </table>
    <button>Submit</button>
<h1>Recent entries</h1>
    <table>
        <tr>
            <th class="field-label">Date</th>
            <th class="field-label">Weight (KG)</th>
            <th class="field-label">Body Fat Percent</th>
        </tr>
        {% for entry in recent %}
        <tr>
            <td class="field-label">{{ entry.date.strftime('%Y-%m-%d') }}</td>
            <td class="field-label">{{ entry.body_weight }}</td>
            <td class="field-label">{{ entry.body_fat_percent }}</td>
        </tr>
        {% endfor %}
    </table>
</form>
{% endblock %}

src/Strand/strand/templates/form_macros.html
{% macro render_field(field) %}
    <tr>
        <td class="form-field-label">{{ field.label }} </td>
        <td class="form-field">{{ field(**kwargs)|safe }}</td>
    </tr>
    {% if field.errors: %}
    <tr>
            <td>
                <ul>
                    {% for error in field.errors %}
                    <li><div class="error-text">{{ error }}</div></li>
                    {% endfor %}
                </ul>
            </td>
    </tr>
    {% endif %}
{% endmacro %}

src/Strand/strand/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="main-container-text-block">
    <div class="main-container-text-block-text">
        <h2>Welcome to Strand!</h2>
        <p>
            We are all friendly folks here.
            <br>Used the various tabs on the left to recording different kinds of metrics.
        </p>
    </div>
</div>
{% endblock %}

src/Strand/strand/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block page_title %}
Strand - Login
{% endblock %}

{% block title_bar %}
Strand - Login
{% endblock %}

{% block content %}
    <header>
            <h1>{{ title_bar }}</h1>
    </header>
    <form action="" method="post">
        {{form.hidden_tag()}}
        <table>
            {{ render_field(form.username, size=50) }}
            {{ render_field(form.password, size=50) }}
            {{ render_field(form.remember_me) }}
        </table>
        <button>Submit</button>
    </form>

{% endblock %}

src/Strand/strand/templates/metrics_log.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<header>
    <h1>Add weight details</h1>
</header>
<form action="" method="post">
    {{form.hidden_tag()}}
    <table>
        {{ render_field(form.date, size=50) }}
        {{ render_field(form.weight, size=50) }}
        {{ render_field(form.body_fat_percent, size=50) }}
        {{ render_field(form.bmi, size=50) }}
        {{ render_field(form.notes, size=50) }}
    </table>
    <button>Submit</button>
<h1>Recent entries</h1>
    <table>
        <tr>
            <th class="field-label">Date</th>
            <th class="field-label">Weight (KG)</th>
            <th class="field-label">Body Fat Percent</th>
            <th class="field-label">BMI</th>
        </tr>
        {% for entry in recent %}
        <tr>
            <td class="field-label">{{ entry.date.strftime('%Y-%m-%d') }}</td>
            <td class="field-label">{{ entry.weight }}</td>
            <td class="field-label">{{ entry.body_fat_percent }}</td>
            <td class="field-label">{{ entry.bmi }}</td>
        </tr>
        {% endfor %}
    </table>
</form>
{% endblock %}

src/Strand/strand/templates/signup.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block page_title %}
Strand - User Signup
{% endblock %}

{% block title_bar %}
Strand - User Signup
{% endblock %}

{% block content %}
    <header>
            <h1>{{ title_bar }}</h1>
    </header>
    <form action="" method="post">
        {{form.hidden_tag()}}
        <table>
            {{ render_field(form.username, size=50) }}
            {{ render_field(form.email, size=50) }}
            {{ render_field(form.password, size=50) }}
            {{ render_field(form.password2, size=50) }}
            {{ render_field(form.submit) }}
        </table>
    </form>

{% endblock %}

src/Strand/strand/templates/weight.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block content %}
<header>
    <h1>Add weight details</h1>
</header>
<form action="" method="post">
    {{form.hidden_tag()}}
    <table>
        {{ render_field(form.body_weight, size=50) }}
        {{ render_field(form.body_fat_percent, size=50) }}
        {{ render_field(form.date, size=50) }}
        {{ render_field(form.notes, size=50) }}
    </table>
    <button>Submit</button>
<h1>Recent entries</h1>
    <table>
        <tr>
            <th class="field-label">Date</th>
            <th class="field-label">Weight (KG)</th>
            <th class="field-label">Body Fat Percent</th>
        </tr>
        {% for entry in recent %}
        <tr>
            <td class="field-label">{{ entry.date.strftime('%Y-%m-%d') }}</td>
            <td class="field-label">{{ entry.body_weight }}</td>
            <td class="field-label">{{ entry.body_fat_percent }}</td>
        </tr>
        {% endfor %}
    </table>
</form>
{% endblock %}